### ISSUE TITLE
학교 코드 검색 API에서 불필요한 정보(관할 교육청 구분)를 수신

### ISSUE THREAD

**Issue by LumpKim** [EntryDSM/Husky#56]
### 문제사항
- 현재 학교 코드를 검색하는 API에서는 검색하고자 하는 중학교가 속한 지역의 관할교육청 정보를 선택해야 합니다.
- '경기도 광주' 지역 관할교육청과 '광주광역시' 지역 관할교육청의 정보를 구분할 명확한 방법이 없습니다.
- DB 스키마 구조 상으로는 관할교육청 구분을 같이 받아야 할 이유 및 근거가 전혀 없으며, 불필요한 추가 쿼리를 발생시켜 성능에 악영향을 끼칩니다.

### 해결방법
- [x] 학교 코드 검색 API에서 지역 관할 교육청 구분을 수신하지 않도록 변경합니다.
  - [x] 디자인 수정
  - [x] 프론트엔드 팀(_Poodle_) 측에 전달
  - [x] Husky 코드 수정

**Comment by huewilliams** [comment]
#66 에서 해결되었습니다.
