### ISSUE TITLE
프로필 이미지 변경 시 이전 이미지가 삭제되지 않음

### ISSUE THREAD

**Issue by LumpKim** [EntryDSM/Husky#63]
### 문제사항
지원자가 지원자 사진을 새로 등록할 때, 기존 이미지를 삭제하는 로직이 누락되어 있습니다. 기존 이미지를 삭제하지 않는다면 이미지가 계속 쌓일 것이고, 이는 비용 증가로 이어져 재정 상 부담이 됩니다.

### 해결방법
- 지원자 이미지 등록 시 기존에 등록된 이미지를 삭제하는 로직을 추가합니다.

**Comment by huewilliams** [comment]
#66 에서 해결되었습니다.
